### ISSUE TITLE
gNMI-1.10 - Telemetry Basic Check: Use of hardcoded component names and parent<->child relationships

### ISSUE THREAD

**Issue by sgirishj** [openconfig/featureprofiles#1002]
https://github.com/openconfig/featureprofiles/blob/7061d7918e7a3131492083a4195b94f4a9e6ba90/feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go#L325

The test 'TestComponentParent' in the above references script appears to be making assumptions regarding the below:
- that components in the device's inventory are named a certain way (e.g. Fabric, Supervisor, etc.)
- that the parent<->child relationships between components/sub-components in the device adhere to what is defined in the test (e.g. 'Chassis' is the parent of 'Fabric' and 'Fabric' is the parent of 'FabricChip')

The OC model around system component inventory defines/enforces neither of the above. Furthermore, names and parent<->child relationships are typically vendor/platform/implementation specific.

@dplore , @greg-dennis - request your inputs on this.

Thanks!

**Comment by dplore** [comment]
This code should be refactored to use the OpenConfig component identities instead of component name strings.

Regarding the parent relationships, this test is targeted for modular form factor devices where these components are expected to be identified by the DUT.    The test should be refactored to use the yang identities instead of the name strings which are vendor specific.  ie: the hierarchy should be defined like: `CHASSIS` <- `FABRIC` <- `INTEGRATED_CIRCUIT`.  

Agreed that the openconfig-platform model does not require this relationship and I acknowledge that all devices may not have these components.  We should clarify this test is intended for modular form factor devices either through documentation or perhaps a parameter such as `modular_form_factor`) which when set requires the parent relationships to exist.  It is then up to the caller to assert if the DUT is required to behave as a modular_form_factor device or not.  When testing a DUT such as a single INTEGRATED_CIRCUIT device which is not expected to have a `FABRIC` component, the invoker would not set this parameter and the test would skip validating the relevant component identities and leafs.

What do you think?

**Comment by earies** [comment]
+1 to not using component name strings anywhere for assumptions - this should be a featureprofile design guideline to not happen again as we've seen this a few times already.  Conclusion - it is up to each implementation to formulate these keys (as are various other mostly r/o keys elsewhere in the model set)

@dplore I know we spoke about this before if we wanted to create or dictate firm parent/child relationships for components but also due to the limited abstract number of component types (the identities you mention above) and differences between platform architectures (even if abstracted to something like a `modular_form_factor`) this will likely still have its set of challenges - TLDR: not all boxes are equal so how precise can this get w/o losing valuable data.  Accuracy is often key here.

The important point here is being able to draw the relationship somehow - whether it is a direct parent or a grandparent, this could occur.  In addition, we have some component types that could be dispersed as children to different components.  e.g. `INTEGRATED_CIRCUIT` could very well be a child of `FABRIC`, `LINECARD` or even something such as a `MODULE` as we discussed in a previous PR (e.g.  a module that resides in a linecard)

Picking on the P4 case as this provides a good example of how to walk relationships.  You have an `interface` that has a `hardware-port` reference back to a component of type `PORT` which needs to have a relationship to an `INTEGRATED_CIRCUIT`  somewhere in its parent path - do we think we can dictate that `PORT` is always a direct descendant of an `INTEGRATED_CIRCUIT` here?  The parent path above this could very well differ however.

**Comment by dplore** [comment]
> Picking on the P4 case as this provides a good example of how to walk relationships. You have an `interface` that has a `hardware-port` reference back to a component of type `PORT` which needs to have a relationship to an `INTEGRATED_CIRCUIT` somewhere in its parent path - do we think we can dictate that `PORT` is always a direct descendant of an `INTEGRATED_CIRCUIT` here? The parent path above this could very well differ however.

Yes, I think we could assert that there must be a direct relationship between `PORT` and `INTEGRATED_CIRCUIT`.  

One way we could do this with a leafref in the /interfaces/interface tree, similar to `interfaces-interface-state-transceiver`.  https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-interfaces.html#interfaces-interface-state-transceiver.  ie:  create a new path like `/interfaces/interface/state/integrated-circuit`.    Positive is this is very simple, clear and explicit, but it is not an algorithmic/programmatic pattern. 

@ejbrever you did some work in the optical side for modeling device internal topology.  Do you have an opinion?

**Comment by dplore** [comment]
The real operational requirement we have will simplify the behavior requirements to something that is more likely to pass across different device types.

Our operational requirement is an `INTEGRATED_CIRCUIT` should be traceable to a `CHASSIS`.    The goal is to derive which INTEGRATED_CIRCUIT's are present on the same chassis (regardless of `LINECARD` or other module). This is important to resolve for example when ports on different INTEGRATED_CIRCUIT's and LINECARD's are members of the same aggregate (LAG) interface.

So the test can be modified to 
* ignore `FABRIC`
* ensure an  INTEGRATED_CIRCUIT component has an ancestor of type `CHASSIS`, iterating through parent's and ignoring the type until `CHASSIS` is found.

**Comment by sachendras** [comment]
`ignore FABRIC`

Are you suggesting to get rid of `Fabric` and `Fabric-chip` tests in https://github.com/openconfig/featureprofiles/blob/cb007634351be57e3b6683e6d10e9115f4f4198c/feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go#L371-L378?

**Comment by dplore** [comment]
I see the code is already [searching for chassis as a parent](https://github.com/openconfig/featureprofiles/blob/cb007634351be57e3b6683e6d10e9115f4f4198c/feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go#L419-L424) and no longer looking for a specific parent type.  
So the test is already agnostic to the component hierarchy except that chassis must be an ancestor.  

We do not currently have a requirement for the FABRIC component to have a parent relationship, although I would expect that to be `CHASSIS`.  If this is a problem, I am okay with removing `FABRIC`.  `FabricChip` should be removed because it is not an OC entity.

Note, we do require the presence of a FABRIC component on modular form factor devices. But this can be covered by other tests which require it.  For example, getting the [capacity of a FABRIC](https://github.com/openconfig/featureprofiles/issues/543) component.

**Comment by sgirishj** [comment]
Thanks! Removed fabricChip from the list of items to be verified. Left fabric in there. Changes pushed through https://github.com/openconfig/featureprofiles/pull/1195.
