### ISSUE TITLE
reuse ATE session id

### ISSUE THREAD

**Issue by mingyangcisco** [openconfig/featureprofiles#123]
When we run the current test via static binding, it creates a new RESTAPI session and then get the ports and run the tests. after test run is done, the session/port is not clean up. If we run the tests with the same port, the test may fail due to port owned by other session. If we re-use the ATE session id, it could help resolve it. Also the current NewSession way in static binding doesn't work with IXIA windows chassis but the FetchSession way works fine with IXIA windows chassis.

**Comment by greg-dennis** [comment]
The IxNetwork logic was really only written to work with the IxNetwork Web Platform. Your Reserve() logic should probably determine which Ixia session you want, whether that be a newly-created session or fetching an existing one from some set of preallocated sessions you've created. If a new one is created, the Release() logic can then delete it. In our experience, creating a new session in reserve is preferable, because IxNetwork tends to misbehave over time with repeated use of the same session. Does that make sense?

**Comment by mingyangcisco** [comment]
https://github.com/openconfig/featureprofiles/pull/122
