### ISSUE TITLE
Need clarification with RT-1.1: Base BGP Session Parameters.

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#185]
Hi,

I Need some clarification regarding RT-1.1: Base BGP Session Parameters.

Test case procedure refers to 'table-based configuration'. Could you please clarify what table based configuration refers to? Screenshot attached for reference.

<>
Establish BGP session on ATE and DUT with **table-based** configuration to cover:
- Explicitly specified Router ID
- MD5 password
</>

Thanks,
Prabha

**Comment by dplore** [comment]
@liulk could you clarify for us?  Is this a suggestion to use a coding pattern similar to [table driven tests](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) but for configuration?  

Example where table driven tests are used in featureprofiles:
https://github.com/openconfig/featureprofiles/blob/5a1aaa3d0a4879b50379c30327ca88cf6b9ac9f1/feature/gribi/ate_tests/weighted_balancing_test/weighted_balancing_test.go#L40-L59

**Comment by liulk** [comment]
We have an early version of RT-1.1 that we implemented using two DUTs instead of one ATE and one DUT, so this would illustrate what a table-driven test looks like:

https://github.com/openconfig/featureprofiles/blob/5a1aaa3d0a4879b50379c30327ca88cf6b9ac9f1/feature/bgp/tests/local_bgp_test/local_bgp_test.go#L157

The reason why it used two DUTs was because back then, the ATE API did not support these BGP parameters we needed for RT-1.1. @dan-lepage for background.

The addition work that needs to be done here is to make a copy of `TestParameters` from local_bgp_test.go and use this ATE API to configure BGP on the Ixia: https://pkg.go.dev/github.com/openconfig/ondatra#Interface.BGP

The new test should be placed under `feature/bgp/ate_tests/base_bgp_session_parameters.go` with the test plan converted to Markdown in `feature/bgp/ate_tests/base_bgp_session_parameters.md`.

Let me know if you have more questions.

**Comment by cprabha** [comment]
Thanks Likai and Darren.
I will make a copy of local_bgp_test.go and update it with ixia APIs.

Thanks,
Prabha

**Comment by cprabha** [comment]
Hi Likai,

I have updated RT1.1 automation and tried to create pull request.
Pull request shows total changes as 11 due to my earlier trail commits to my forked repo.

I tried to create new fork now, its not allowing.
Is it fine to go ahead with this pull request , please let me know.

https://github.com/openconfig/featureprofiles/pull/201

Thanks,
Prabha



Juniper Business Use Only

**Comment by liulk** [comment]
Let's continue any further discussion about [#201](https://github.com/openconfig/featureprofiles/pull/201) there.
