### ISSUE TITLE
local_bgp_test.go: Supported keepalive and hold timer values

### ISSUE THREAD

**Issue by aredmon8551** [openconfig/featureprofiles#275]
In one instance of local_bgp_test.go, the keepalive timer is set to 50 and the hold-timer is set to 100 seconds.  
https://github.com/openconfig/featureprofiles/blob/main/feature/bgp/tests/local_bgp_test/local_bgp_test.go#L239

BGP's RFC suggests a keepalive timer of hold-down/3:
   `A reasonable maximum time between KEEPALIVE messages would be one third
   of the Hold Time interval.  KEEPALIVE messages MUST NOT be sent more
   frequently than one per second.  An implementation MAY adjust the
   rate at which it sends KEEPALIVE messages as a function of the Hold
   Time interval.`

Note, too, that only the hold-timer is conveyed in BGP OPEN messages - the keepalive must be derived (or explicitly configured) by both peers.  Keepalive intervals are largely locally significant, as well - as long as one is received (or an UPDATE message) within the hold-down period then the session will remain ESTABLISHED.

Juniper only supports keepalive values of hold-down/3 - this is a fundamental behavior of our implementation that cannot be easily changed.  

Can we update this test case to use values that align with the RFC's guidance and can be supported by all major vendor implementations by using the formula of hold-down = keepalive * 3?

Edit: grammar

**Comment by dplore** [comment]
@bstoll what do you think?

**Comment by jhaas-pfrc** [comment]
I had been asked to look into this issue as part of internal reviews.  This sort of issue comes up every few years.

BGP's core specification, RFC 4271 in section 10, provides this guidance:

   An implementation of BGP MUST allow the HoldTimer to be configurable
   on a per-peer basis, and MAY allow the other timers to be
   configurable.

It's quite fine for an implementation to support a configurable keepalive timer.  Requiring it to be configurable means the test case is out of variance with the RFC.

I will also advise that tests against the timers of conformant implementations have a tendency to be fragile due to excess pedantry.  Implementations are generally expected to apply jitter.  From the same section of the RFC:

To minimize the likelihood that the distribution of BGP messages by a
   given BGP speaker will contain peaks, jitter SHOULD be applied to the
   timers associated with MinASOriginationIntervalTimer, KeepaliveTimer,
   MinRouteAdvertisementIntervalTimer, and ConnectRetryTimer.  A given
   BGP speaker MAY apply the same jitter to each of these quantities,
   regardless of the destinations to which the updates are being sent;
   that is, jitter need not be configured on a per-peer basis.

   The suggested default amount of jitter SHALL be determined by
   multiplying the base value of the appropriate timer by a random
   factor, which is uniformly distributed in the range from 0.75 to 1.0.
   A new random value SHOULD be picked each time the timer is set.  The
   range of the jitter's random value MAY be configurable.

-- Jeff Haas, IDR co-chair and someone who has been through way too many conformance test iterations with multiople organizations.

**Comment by aredmon8551** [comment]
Hey @bstoll - any thoughts?

**Comment by bstoll** [comment]
[OpenConfig](https://github.com/openconfig/public/blob/master/release/models/bgp/openconfig-bgp-common.yang#L159) mentions this 1/3 ratio.  From a practical POV I don't think we have a use case that is worth the effort here.  I think this may have just been an oversight when the test was written.  I will look at changing the test.

**Comment by dplore** [comment]
I also support changing the test to 
1. set the holdtimer explicitly 
2.  attempt to set the keepalive timer to 3x the holdtimer value, but allow the keepalive timer setRequest to fail.  
3.  retain verification that the keepalive timer is 3x the holdtimer value.

**Comment by jhaas-pfrc** [comment]
I suggest the following cases:
1. If holdtimer is configured and keepalive timer is not, expect keepalive timer to fire at 1/3 of the time (minus jitter), holdtimer fires as configured.
2. If keepalive timer is configured and holdtimer is not, expect keepalive timer to fire at the configured time (minus jitter), holdtimer fires at 3x keepalive timer.
3. If both are configured, and both are permitted to configured, verify each fires according to their configuration (minus jittter for keepalive timer).

Ambiguous case, alternative 1: if both are configured, both accept configuration, but implementation doesn't support explicit configuration of keepalive timer when hold timer is specified, expected results is likely hold timer fires as configured, keepalive timer value as configured is ignored and fires at 1/3 of holdtimer (minus jitter).

Ambiguous case, alternative 2: if both are configured, both accept configuration, but implementation doesn't support explicit configuration of keepalive timer when hold timer is specified, expected results could be the hold time value may be max(holdtimer, 3 * keepalivetimer), keepalivetimer = 1/3 this calculated value (minus jitter).

If deviations weren't frowned upon in OC modules, the easy answer remains to deviate away keepalivetimer as a configurable item when it's not supported explicitly.  (This would be consistent with the model vs. RFC 4271.)  In the absence of such deviations, resolving the ambiguity through text in the leaf descriptions would be helpful.
