### ISSUE TITLE
gNOI-6.1 Factory reset Encryption requirement

### ISSUE THREAD

**Issue by MarcCharlebois** [openconfig/featureprofiles#3053]
**Describe the bug**
I was looking at factory reset test and was wondering if it's a hard requirement for the test to perform the operation under encrypted/non-encrypted disks.

Additionally, shouldn't there be a dut.vendor() switch to handle the filesystem path where the file would be written/read from to ease vendor implementation as opposed to being called [in variable](https://github.com/openconfig/featureprofiles/blob/4021000445dd0e1f12558a2461fdae801d7a5c91/feature/gnoi/factory_reset/tests/factory_reset_test/factory_reset_test.go#L127)

**Comment by dplore** [comment]
My naive thought is gnoi factory reset test should not need to be aware of disk encryption.  The current test could be refactored to move the encryption actions specific to Cisco into a deviation that only applies to Cisco, rather than being part of the test requirements.

Do most implementations require enabling / disabling encryption in order to do an install?  If yes, we should move these operations into gnoi proto, and not deviations with bash commands.

For filename handling, I think the test should be refactored to remove the need to filenames. Rather than creating a file and then checking that it is deleted to confirm factory reset, another method would be to set some configuration before the reset and then confirm it is removed after the reset.

**Comment by MarcCharlebois** [comment]
>Do most implementations require enabling / disabling encryption in order to do an install? If yes, we should move these operations into gnoi proto, and not deviations with bash commands.

I don't think so, but perhaps other vendors could comment on this.

> For filename handling, I think the test should be refactored to remove the need to filenames. Rather than creating a file and then checking that it is deleted to confirm factory reset, another method would be to set some configuration before the reset and then confirm it is removed after the reset.

Since this is a gNOI test, would it be acceptable to use gNOI File Put/gNOI File Stat for this check. While I think it may also be a good idea to look at configuration, I also think it could be problematic - if the DUTs are configured to be bootstrapped via ZTP, some config may be pushed to the DUT.

**Comment by LimeHat** [comment]
>My naive thought is gnoi factory reset test should not need to be aware of disk encryption. 

That was our thinking as well.

If there's a need to validate enabling/disabling disk encryption through cli, we think it should be a separate test (although disabling the encryption, in general, is uncommon)
