### ISSUE TITLE
TE-11.2: Backup NHG: Multiple NH

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#70]

**Comment by manan-patel** [comment]
Hi,

Since the TC is very basic, we were suggesting uplifting them. Please advise if this is the way to go or if we should stick with the TC provided. 

Uplift suggested:
default case has PBR, isis, and BGP configured on DUT
we set up 2 flows, 1st for the isis prefix and 2nd BGP prefix for traffic validation 

Instead of a single TC, we are adding 2 more TC
1: TE 11.2 
2: backup pointing to drop address (as per ip-in-ip document)
3: backup pointing to decap (as per ip-in-ip document), decap traffic carried via BGP (BGP prefix is resolved over ISIS), TC also has 2 level of programming scenario

**Comment by xw-g** [comment]
Thanks @manan-patel. 

2) is not our focus for now. 
3) will be handled by TE-11.3 (will be published soon)

I'll chat more with you in another thread. Closing this issue for now :).

**Comment by dplore** [comment]
Reopening because this test is not implemented now. Labeled 'not-ready', which indicates that the test requirements are not complete.

**Comment by manan-patel** [comment]
I have PR open for it
https://github.com/openconfig/featureprofiles/pull/403
