### ISSUE TITLE
gNMI-1.12 mixed origin precedence

### ISSUE THREAD

**Issue by liulk** [openconfig/featureprofiles#740]
gNMI-1.12 as currently written follows the gNMI spec where updates are applied in the order they appear in the SetRequest, which means if there are conflicting updates with both OC and CLI origins, whichever appears last takes effect.

https://github.com/openconfig/featureprofiles/pull/474#discussion_r960839510

> https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#34-modifying-state
> 
> The order of the replace and update fields MUST be treated as significant within a single SetRequest message. If a single path is specified multiple times for a single operation (i.e., within update or replace), then the state of the target MUST reflect the application of all of the operations in order, even if they overwrite each other.

But the concern is that this is not the way implementations are built today. This prompted more discussion in the wider OC community. Rather than tracking the discussion in an already merged PR, this issue has been created where discussion can take place. If a verdict is reached, then we can change the test plan and the test.

**Comment by rgwilton** [comment]
Expanding on my comments on the call:

For me, I think key point at an external data model level whether the same or different data nodes are being written for "CL"I vs "OC YANG".

If there are multiple edits to the same external data node, then the last edit to that data node takes effect. This is common sense intuition and matches all other management protocols.

The case where it is necessary to perform a merge operation is where a single internal configuration property is set (directly or indirectly) by two or more data nodes in the external models. At the top level, there are two cases to consider:

1) In the case that the two (or more) external data nodes that are being mapped are all in the same model family (e.g., both are in OC YANG) then if we cannot consistently map those external values into the equivalent internal configuration property then we must reject the configuration change, because otherwise we would not be enacting some of the OC configuration, and the client would have no way of knowing value in the OC model has precedence. This behavior applies whether the OC configuration is configured explicitly or an in-scope default value (e.g., a parent list entry has been created). An example of such a configuration mapping issue is where there is only a coarse config knob in the internal model and more fine-grained equivalent config knobs in the external model). It is possible to map the set of fine-grained config knobs in the external model to the coarse config knob in the internal model as long they consistently collectively map to the same value for the coarse config knob. Note, the ideal solution here is to extend the internal model with fine-grained config knobs as well.
2) The second case is where the two external data nodes being mapped are in different model families (e.g., one is configured via a device native CLI, and the other is configured via OC YANG). This is the scenario where it is far more likely that very similar of equivalent configuration exists in both OC and Native model families. This scenario is also more complex, since it must consider how: a) two explicitly configured values interact, b) how explicitly configured values in one model interact with in-scope default values in the other model, and c) how in-scope default values between the two model families interact.

For the second option, I believe that the most consistent semantics (for OC) are:

1) If conflicting explicitly configured values are configured in two model families, then the configuration should be rejected. E.g., if the client explicitly configures MTU 4000 in OC, and explicitly configures MTU 3000 in the CLI/Native then the right thing to do here is to reject the configuration change.
2) Any explicitly configured value overrides a default/implicit value from another model family. E.g., an explicitly configured interface MTU in OC should override the device default MTU for the interface in the CLI/Native schema, even if that interface has been configured in the CLI/Native configuration, e.g., to enable some other per-interface config knob not expressed in the OC schema.
3) In the case where there are different in-scope default values between the two external model families that are getting mapped, then the default value from the OC model family should take precedence over the default value in the native model family. E.g., if OC defined the default MTU of an interface to be 2000 bytes, and the CLI/Native schema defined the default MTU of an interface to be 1500 bytes, and the interface existed in both CLI/Native & OC configuration, then since the assumption is that the device is primarily being configured via OC then the default value in OC should override the default value in the CLI/Native schema.

Finally, there are a couple of variants to the options above:

1) It should probably be possible via device level configuration to allow the client to decide which configuration family takes precedence (e.g., CLI/Native or OC), depending on whether the device is primarily being configured via OC or via CLI/Native.

2) Rather than rejecting conflicting explicitly configured values, one could instead allow them to be resolved the same way as for defaults. In yesterday's call, I think that there was a suggestion that the value configured on the CLI should take precedence over an OC configured, but I suspect that this would be confusing in many deployments unless conflicting defaults values are handled similarly.  Ultimately, I think that explicitly rejecting conflicting values is like to cause less surprise for clients and is a probably better way to go.

Rob

**Comment by dplore** [comment]
This issue is obsoleted by https://github.com/openconfig/reference/pull/188
